SetDirectory["/var/www/html/sig"];
fn=FileNames["*.jpg"];
sigData=Table[Import[a],{a,fn}];
SetDirectory["/var/www/html/con"];
fn=FileNames["*.jpg"];
conData=Table[Import[a],{a,fn}];
imageDivide[img1_,img2_]:=Module[{work},
				 work=img2//ImageData//Map[Function[a,If[a==0.,1,1/a]],#,{2}]&//Image;
				 ImageMultiply[img1,work]
				 ];
analysis[sig_,con_,gaussianFilterR_,erosionR_,fraction_]:=Module[{sigImg,conImg,threshold,mask,transmittance,transData,intensity,checkSaturation,saturationNumber},
								   sigImg=sig//ImageCrop[#,ImageDimensions[#]+20]&//GaussianFilter[#,gaussianFilterR]&;
								   conImg=con//ImageCrop[#,ImageDimensions[#]+20]&//GaussianFilter[#,gaussianFilterR]&;
								   threshold=sigImg//FindThreshold[#,Method->"Cluster"]&;
								   mask=sigImg//Binarize[#,threshold]&//Erosion[Pruning[#],DiskMatrix[erosionR]]&;
								   transmittance=imageDivide[sigImg,conImg]//ImageMultiply[#,mask]&;
								   transData=transmittance//ImageData//Flatten//DeleteCases[#,0.]&;
								   intensity=transData//TrimmedMean[#,fraction]&;
								   checkSaturation=transmittance//ImageData//Flatten;
								   saturationNumber=checkSaturation//Count[#,1.]&;
								   intensity
								 ];
key="X0CQRTZDMYW0JZHX";
transmittance=analysis[sigData[[1]]//ColorSeparate[#,"RGB"]&//Part[#,2]&,conData[[1]]//ColorSeparate[#,"RGB"]&//Part[#,2]&,5,5,0.1];
Import[URLBuild[{"http://192.168.2.1:3000","update"},{"key"->key,"field1"->transmittance*RandomReal[]}]];
Quit
