   keyfile = "./ChannelAndField";
   obj = Import[keyfile];
   Stringnum = StringSplit[obj, ","];
   Channel = Stringnum[[1]];
   Field = Stringnum[[2]];
   Method1 = Stringnum[[3]];
   Result = Stringnum[[4]];
   rannum = Random[Integer,{0,99}];
   strr = ToString[rannum];
   Export["./randomArray/C"<>Channel<>"F"<>Field,rannum,"Text"];
   integralURL = "http://localhost:3000/channels/" <> Channel <> "/fields/" <> Field <> ".json?results="<>Result;
   JsonData = Import[integralURL, "JSON"];
   Allfeeds = "feeds" /. JsonData;
   fieldid = "field" <> Field;
   AllData = fieldid /. Allfeeds // ToExpression;
   AllDatasize = Length[AllData];
   AllDataMean = Mean[AllData];
   AllDatacenter = (Max[AllData] + Min[AllData])/2;
   allDatasize = ALlDatasize;
   allData = AllData;
   allDatasize = Length[allData];
   allkey = Range[allDatasize];
   alltable = Transpose[{allkey, allData}];
   trNeuron = Association @@ Rule @@@ alltable;
   fitNeuron = Predict[Normal@trNeuron, Method -> "GaussianProcess"];
   P = Show[Plot[fitNeuron[x], {x, 0, allDatasize}, PlotStyle -> Red,PlotRange -> All], ListPlot[trNeuron]];
   FieldDirectory = "./savedimage/" <> Channel <> "/"<> Method1 <>"/"<> Result <> "/";
   If[DirectoryQ[FieldDirectory], null , CreateDirectory[FieldDirectory]];
   Export["./savedimage/"<> Channel <>"/"<> Method1 <>"/"<> Result <>"/field"<> Field <>"_"<> strr <> ".png", P];
   Quit
